name: iteeha_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
# Iteeha Code

version: 1.0.2+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  pin_code_fields: ^8.0.1
  flutter_svg: ^1.1.1+1
  localstorage: ^4.0.0+1
  shared_preferences: ^2.0.7
  provider: ^6.0.3
  carousel_slider: ^5.1.1
  intl: ^0.18.0
  firebase_messaging: ^14.7.10
  flutter_local_notifications: ^19.4.0
  firebase_core: ^2.8.0
  image_picker: ^0.8.3+3
  email_validator: ^2.0.1
  url_launcher: ^6.0.9
  flutter_html: ^3.0.0-alpha.5
  google_maps_flutter: ^2.5.0
  geolocator: ^10.0.1
  permission_handler: ^12.0.1
  razorpay_flutter: ^1.3.0
  # badges: ^2.0.3
  otp_autofill: ^4.1.0
  cached_network_image: ^3.2.2
  # path_provider: ^2.0.11
  # video_compress: ^3.1.2
  # video_player: ^2.4.5
  # chewie: ^1.2.2
  # share: ^2.0.4
  firebase_dynamic_links: ^5.3.6
  # barcode_scan: ^3.0.0
  barcode_widget: ^2.0.4
  share_plus: ^7.2.1 
  animated_size_and_fade: ^3.0.1
  app_settings: ^5.1.1
  shimmer: ^2.0.0
  webview_flutter: ^4.4.2
  device_info_plus: ^11.2.2
  flutter_launcher_icons: ^0.13.1


  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

dependency_overrides:
  # ffi: ^2.0.1


flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/app_logo.png"


flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/images/corousel/
    - assets/svgIcons/
    - assets/placeholders/


  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Inter-Medium.ttf
          weight: 500
        - asset: assets/fonts/Inter-Bold.ttf
          weight: 900
    - family: Inria Serif
      fonts:
        - asset: assets/fonts/InriaSerif-Regular.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: LT Superior
      fonts:
        - asset: assets/fonts/LTSuperior-Black.otf
        - asset: assets/fonts/LTSuperior-Bold.otf
        - asset: assets/fonts/LTSuperior-ExtraBold.otf
        - asset: assets/fonts/LTSuperior-ExtraLight.otf
        - asset: assets/fonts/LTSuperior-Light.otf
        - asset: assets/fonts/LTSuperior-Medium.otf
        - asset: assets/fonts/LTSuperior-Regular.otf
        - asset: assets/fonts/LTSuperior-SemiBold.otf
        - asset: assets/fonts/LTSuperior-Thin.otf

        

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
